from django.db import models
from django.contrib.auth.models import AbstractUser


class User(AbstractUser):
    nickname = models.CharField(max_length=50, blank=True)

    class Meta(AbstractUser.Meta):
        pass


class simaoyou(models.Model):
    place = models.CharField(max_length=5,default='smy')
    data1 = models.FloatField(default=1, null=True)
    data2 = models.FloatField(default=2,null=True)
    data3 = models.FloatField(default=3,null=True)
    data4 = models.FloatField(default=4,null=True)
    data5 = models.FloatField(default=5,null=True)
    data6 = models.FloatField(default=6,null=True)
    data7 = models.FloatField(default=7,null=True)
    data8 = models.FloatField(default=8,null=True)
    data9 = models.FloatField(default=9,null=True)
    data10 = models.FloatField(default=10,null=True)
    data11 = models.FloatField(default=11,null=True)
    data12 = models.FloatField(default=12, null=True)
    data13 = models.FloatField(default=13, null=True)
    data14 = models.FloatField(default=14, null=True)
    data15 = models.FloatField(default=15, null=True)
    data16 = models.FloatField(default=16, null=True)
    data17 = models.FloatField(default=17, null=True)
    data18 = models.FloatField(default=18, null=True)
    data19 = models.FloatField(default=19, null=True)
    data20 = models.FloatField(default=20, null=True)
    data21 = models.FloatField(default=21, null=True)
    data22 = models.FloatField(default=22, null=True)
    data23 = models.FloatField(default=23, null=True)
    data24 = models.FloatField(default=24, null=True)
    data25 = models.FloatField(default=25, null=True)
    data26 = models.FloatField(default=26, null=True)
    data27 = models.FloatField(default=27, null=True)
    data28 = models.FloatField(default=28, null=True)
    data29 = models.FloatField(default=29, null=True)
    data30 = models.FloatField(default=30, null=True)
    data31 = models.FloatField(default=31, null=True)
    data32 = models.FloatField(default=32, null=True)
    data33 = models.FloatField(default=33, null=True)
    data34 = models.FloatField(default=34, null=True)
    data35 = models.FloatField(default=35, null=True)
    data36 = models.FloatField(default=36, null=True)
    data37 = models.FloatField(default=37, null=True)
    data38 = models.FloatField(default=38, null=True)
    data39 = models.FloatField(default=39, null=True)
    data40 = models.FloatField(default=40, null=True)
    data41 = models.FloatField(default=41, null=True)
    data42 = models.FloatField(default=42, null=True)
    data43 = models.FloatField(default=43, null=True)
    data44 = models.FloatField(default=44, null=True)
    data45 = models.FloatField(default=45, null=True)
    data46 = models.FloatField(default=46, null=True)
    data47 = models.FloatField(default=47, null=True)
    addtime = models.DateTimeField(auto_now_add=True)
    def __unicode__(self):
         return self.name

class xinyanggang(models.Model):
    place = models.CharField(max_length=5,default='xyg')
    data1 = models.FloatField(default=1, null=True)
    data2 = models.FloatField(default=2,null=True)
    data3 = models.FloatField(default=3,null=True)
    data4 = models.FloatField(default=4,null=True)
    data5 = models.FloatField(default=5,null=True)
    data6 = models.FloatField(default=6,null=True)
    data7 = models.FloatField(default=7,null=True)
    data8 = models.FloatField(default=8,null=True)
    data9 = models.FloatField(default=9,null=True)
    data10 = models.FloatField(default=10,null=True)
    data11 = models.FloatField(default=11,null=True)
    data12 = models.FloatField(default=12, null=True)
    data13 = models.FloatField(default=13, null=True)
    data14 = models.FloatField(default=14, null=True)
    data15 = models.FloatField(default=15, null=True)
    data16 = models.FloatField(default=16, null=True)
    data17 = models.FloatField(default=17, null=True)
    data18 = models.FloatField(default=18, null=True)
    data19 = models.FloatField(default=19, null=True)
    data20 = models.FloatField(default=20, null=True)
    data21 = models.FloatField(default=21, null=True)
    data22 = models.FloatField(default=22, null=True)
    data23 = models.FloatField(default=23, null=True)
    data24 = models.FloatField(default=24, null=True)
    data25 = models.FloatField(default=25, null=True)
    data26 = models.FloatField(default=26, null=True)
    data27 = models.FloatField(default=27, null=True)
    data28 = models.FloatField(default=28, null=True)
    data29 = models.FloatField(default=29, null=True)
    data30 = models.FloatField(default=30, null=True)
    data31 = models.FloatField(default=31, null=True)
    data32 = models.FloatField(default=32, null=True)
    data33 = models.FloatField(default=33, null=True)
    data34 = models.FloatField(default=34, null=True)
    data35 = models.FloatField(default=35, null=True)
    data36 = models.FloatField(default=36, null=True)
    data37 = models.FloatField(default=37, null=True)
    data38 = models.FloatField(default=38, null=True)
    data39 = models.FloatField(default=39, null=True)
    data40 = models.FloatField(default=40, null=True)
    data41 = models.FloatField(default=41, null=True)
    data42 = models.FloatField(default=42, null=True)
    data43 = models.FloatField(default=43, null=True)
    data44 = models.FloatField(default=44, null=True)
    data45 = models.FloatField(default=45, null=True)
    data46 = models.FloatField(default=46, null=True)
    data47 = models.FloatField(default=47, null=True)
    addtime = models.DateTimeField(auto_now_add=True)
    def __unicode__(self):
         return self.name
class panjin(models.Model):
    place = models.CharField(max_length=5,default='pj')
    data1 = models.FloatField(default=1, null=True)
    data2 = models.FloatField(default=2,null=True)
    data3 = models.FloatField(default=3,null=True)
    data4 = models.FloatField(default=4,null=True)
    data5 = models.FloatField(default=5,null=True)
    data6 = models.FloatField(default=6,null=True)
    data7 = models.FloatField(default=7,null=True)
    data8 = models.FloatField(default=8,null=True)
    data9 = models.FloatField(default=9,null=True)
    data10 = models.FloatField(default=10,null=True)
    data11 = models.FloatField(default=11,null=True)
    data12 = models.FloatField(default=12, null=True)
    data13 = models.FloatField(default=13, null=True)
    data14 = models.FloatField(default=14, null=True)
    data15 = models.FloatField(default=15, null=True)
    data16 = models.FloatField(default=16, null=True)
    data17 = models.FloatField(default=17, null=True)
    data18 = models.FloatField(default=18, null=True)
    data19 = models.FloatField(default=19, null=True)
    data20 = models.FloatField(default=20, null=True)
    data21 = models.FloatField(default=21, null=True)
    data22 = models.FloatField(default=22, null=True)
    data23 = models.FloatField(default=23, null=True)
    data24 = models.FloatField(default=24, null=True)
    data25 = models.FloatField(default=25, null=True)
    data26 = models.FloatField(default=26, null=True)
    data27 = models.FloatField(default=27, null=True)
    data28 = models.FloatField(default=28, null=True)
    data29 = models.FloatField(default=29, null=True)
    data30 = models.FloatField(default=30, null=True)
    data31 = models.FloatField(default=31, null=True)
    data32 = models.FloatField(default=32, null=True)
    data33 = models.FloatField(default=33, null=True)
    data34 = models.FloatField(default=34, null=True)
    data35 = models.FloatField(default=35, null=True)
    data36 = models.FloatField(default=36, null=True)
    data37 = models.FloatField(default=37, null=True)
    data38 = models.FloatField(default=38, null=True)
    data39 = models.FloatField(default=39, null=True)
    data40 = models.FloatField(default=40, null=True)
    data41 = models.FloatField(default=41, null=True)
    data42 = models.FloatField(default=42, null=True)
    data43 = models.FloatField(default=43, null=True)
    data44 = models.FloatField(default=44, null=True)
    data45 = models.FloatField(default=45, null=True)
    data46 = models.FloatField(default=46, null=True)
    data47 = models.FloatField(default=47, null=True)
    addtime = models.DateTimeField(auto_now_add=True)
    def __unicode__(self):
         return self.name

class TheYellowRiverDelta(models.Model):
    place = models.CharField(max_length=5,default='hhzjz')
    data1 = models.FloatField(default=1, null=True)
    data2 = models.FloatField(default=2,null=True)
    data3 = models.FloatField(default=3,null=True)
    data4 = models.FloatField(default=4,null=True)
    data5 = models.FloatField(default=5,null=True)
    data6 = models.FloatField(default=6,null=True)
    data7 = models.FloatField(default=7,null=True)
    data8 = models.FloatField(default=8,null=True)
    data9 = models.FloatField(default=9,null=True)
    data10 = models.FloatField(default=10,null=True)
    data11 = models.FloatField(default=11,null=True)
    data12 = models.FloatField(default=12, null=True)
    data13 = models.FloatField(default=13, null=True)
    data14 = models.FloatField(default=14, null=True)
    data15 = models.FloatField(default=15, null=True)
    data16 = models.FloatField(default=16, null=True)
    data17 = models.FloatField(default=17, null=True)
    data18 = models.FloatField(default=18, null=True)
    data19 = models.FloatField(default=19, null=True)
    data20 = models.FloatField(default=20, null=True)
    data21 = models.FloatField(default=21, null=True)
    data22 = models.FloatField(default=22, null=True)
    data23 = models.FloatField(default=23, null=True)
    data24 = models.FloatField(default=24, null=True)
    data25 = models.FloatField(default=25, null=True)
    data26 = models.FloatField(default=26, null=True)
    data27 = models.FloatField(default=27, null=True)
    data28 = models.FloatField(default=28, null=True)
    data29 = models.FloatField(default=29, null=True)
    data30 = models.FloatField(default=30, null=True)
    data31 = models.FloatField(default=31, null=True)
    data32 = models.FloatField(default=32, null=True)
    data33 = models.FloatField(default=33, null=True)
    data34 = models.FloatField(default=34, null=True)
    data35 = models.FloatField(default=35, null=True)
    data36 = models.FloatField(default=36, null=True)
    data37 = models.FloatField(default=37, null=True)
    data38 = models.FloatField(default=38, null=True)
    data39 = models.FloatField(default=39, null=True)
    data40 = models.FloatField(default=40, null=True)
    data41 = models.FloatField(default=41, null=True)
    data42 = models.FloatField(default=42, null=True)
    data43 = models.FloatField(default=43, null=True)
    data44 = models.FloatField(default=44, null=True)
    data45 = models.FloatField(default=45, null=True)
    data46 = models.FloatField(default=46, null=True)
    data47 = models.FloatField(default=47, null=True)
    addtime = models.DateTimeField(auto_now_add=True)
    def __unicode__(self):
         return self.name